# Generated by Django 3.1 on 2020-10-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aqidata',
            old_name='pm_10',
            new_name='aqi_100',
        ),
        migrations.RenameField(
            model_name='aqidata',
            old_name='pm_25',
            new_name='aqi_25',
        ),
        migrations.AlterField(
            model_name='aqidata',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
